In [1]:
# creating vectors
import numpy as np

In [2]:
# two tiny 3D vectors
a=np.array([2,1,3])
b=np.array([1,3,3])
print(a)
print(b)

[2 1 3]
[1 3 3]


In [3]:
# vector operations (addition and subtraction)

add_ab = a+b
sub_ab = a-b

print(add_ab)
print(sub_ab)

[3 4 6]
[ 1 -2  0]


In [ ]:
# Dot product (similarity of direction)
# positive হলে একই দিকে, 0 এর কাছাকাছি হলে perpendicular, negative হলে বিপরীত দিকে
#manual dot product: sum of pairwise products

dot_manual=a[0]*b[0]+a[1]*b[1]+a[2]*b[2]

dot_np=np.dot(a,b) # বা a@b
print(dot_manual)
print(dot_np)

14
14


In [5]:
# Norms (Length orr Magnitude of vector)
# L2 norm, the usual length
l2_a=np.linalg.norm(a)
print(l2_a)
l1_a=np.linalg.norm(a,ord=1)
print(l1_a)

3.7416573867739413
6.0


In [6]:
# Normalizing a vectorr (unit vector)

unit_a = a/np.linalg.norm(a)
len_unit_a=np.linalg.norm(unit_a)
print(unit_a)
print(len_unit_a)

[0.53452248 0.26726124 0.80178373]
1.0
