In [18]:
import torch

data= torch.tensor(
    [
        [2, 3, 3],
        [5, 6, 4],
        [7, 8, 5]
    ]
)
data

tensor([[2, 3, 3],
        [5, 6, 4],
        [7, 8, 5]])

In [19]:
X=data[:, 0:2].float()
y=data[:, 2].float()

In [20]:
X

tensor([[2., 3.],
        [5., 6.],
        [7., 8.]])

In [21]:
y

tensor([3., 4., 5.])

# Weight Initialization

In [22]:
# W=1, b=0
def initialize_parameters():
    parameters={}
    
    parameters['W1'] = torch.ones((2, 2))* 0.1
    parameters['b1'] = torch.zeros((2, 1))
    
    parameters['W2'] = torch.ones((2, 1)) * 0.1
    parameters['b2'] = torch.zeros((1, 1))
    
    return parameters

In [23]:
initialize_parameters()

{'W1': tensor([[0.1000, 0.1000],
         [0.1000, 0.1000]]),
 'b1': tensor([[0.],
         [0.]]),
 'W2': tensor([[0.1000],
         [0.1000]]),
 'b2': tensor([[0.]])}

# Better way

In [24]:
def initialize_parameters(layer_dims):
    torch.manual_seed(3)
    parameters={}
    L= len(layer_dims)
    
    for l in range(1, L):
        parameters['W' + str(l)] = torch.ones((layer_dims[l - 1], layer_dims[l])) * 0.1
        parameters['b' + str(l)] = torch.zeros((layer_dims[l], 1))
        
    return parameters

In [25]:
initialize_parameters([2, 2, 1])

{'W1': tensor([[0.1000, 0.1000],
         [0.1000, 0.1000]]),
 'b1': tensor([[0.],
         [0.]]),
 'W2': tensor([[0.1000],
         [0.1000]]),
 'b2': tensor([[0.]])}

# Forward Propagation

In [26]:
def linear_forward(A_prev, W, b):
    Z = torch.matmul(W.T, A_prev) + b
    return Z

In [27]:
def L_layer_forward(X, parameters):
    A = X
    L = len(parameters)//2
    
    for l in range(1, L+1):
        A_prev = A
        
        wl = parameters['W' + str(l)]
        bl = parameters['b' + str(l)]
        A = linear_forward(A_prev, wl, bl)
        
    return A, A_prev

In [28]:
X

tensor([[2., 3.],
        [5., 6.],
        [7., 8.]])

In [29]:
params= initialize_parameters([2, 2, 1])
X_sampel = X[0].reshape(2, 1)
y_hat, A1 = L_layer_forward(X_sampel, params)

In [30]:
y_hat

tensor([[0.1000]])

In [33]:
A1

tensor([[0.5000],
        [0.5000]])

In [34]:
(y - y_hat) ** 2 # lose

tensor([[ 8.4100, 15.2100, 24.0100]])

In [35]:
params

{'W1': tensor([[0.1000, 0.1000],
         [0.1000, 0.1000]]),
 'b1': tensor([[0.],
         [0.]]),
 'W2': tensor([[0.1000],
         [0.1000]]),
 'b2': tensor([[0.]])}