torch অনেকটা numpy এর মত কাজ করে

In [1]:
import torch
print(torch.__version__)

2.11.0+cu130


In [2]:
if torch.cuda.is_available():
    print('GPU is avilable')
    print(f'Device name {torch.cuda.get_device_name(0)}')
else:
    print('GPU is not avilable')

GPU is avilable
Device name NVIDIA GeForce RTX 3050 Ti Laptop GPU


In [3]:
a= torch.empty(2, 3)
a

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [4]:
type(a)

torch.Tensor

In [5]:
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
torch.ones(3, 4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [7]:
torch.rand(2, 3)

tensor([[0.7292, 0.7001, 0.5119],
        [0.4572, 0.6587, 0.8553]])

In [8]:
torch.manual_seed(100) # এটা দিলে যত বারই run করি same value দিবে
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [9]:
torch.tensor([[1, 2, 3], [4, 5, 6]]) # নিজের বানানো array

tensor([[1, 2, 3],
        [4, 5, 6]])

In [10]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [11]:
print(torch.arange(0, 10, 2)) # 0 to 10 value দিবে ২ করে step
print(torch.arange(0, 10, 1)) # 0 to 10 value দিবে 1 করে step

tensor([0, 2, 4, 6, 8])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [12]:
torch.linspace(1, 10, 10)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

# Tensors Shape

In [13]:
x= torch.tensor([[1,2,3], [4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [14]:
x.shape

torch.Size([2, 3])

In [15]:
torch.empty_like(x) # x এর shape এর মত, empty tensor বানবে

tensor([[0, 0, 0],
        [0, 0, 0]])

In [16]:
torch.ones_like(x) # x এর shape এর মত, one নিয়ে tensor বানবে

tensor([[1, 1, 1],
        [1, 1, 1]])

In [17]:
torch.rand_like(x, dtype=torch.float32) # x এর shape এর মত, random (float বলে দিছি, অন্য কিছুও বলা যাইত) নিয়ে tensor বানবে

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

# Data types

In [18]:
x.dtype

torch.int64

In [19]:
torch.tensor([1.0, 2.3, 3.0, 4.5], dtype=torch.int32) # data টা float কিন্তু আমরা চাচ্ছি int এ

tensor([1, 2, 3, 4], dtype=torch.int32)

In [20]:
torch.tensor([1, 2, 4, 5], dtype=torch.float32) # data টা int কিন্তু আমরা চাচ্ছি float এ

tensor([1., 2., 4., 5.])

In [21]:
print('প্রথমে এটা int ছিল: ',x.dtype)
x=x.to(torch.float32)
print(x)
print('convert করে এখন এটাকে flot করা হল: ',x.dtype)

প্রথমে এটা int ছিল:  torch.int64
tensor([[1., 2., 3.],
        [4., 5., 6.]])
convert করে এখন এটাকে flot করা হল:  torch.float32


# Mathematical operations

In [22]:
x= torch.tensor([[1,2,3], [4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

```সব গুলা value এর সাথে +, -, *, / হয়ে যাবে```

In [23]:
x+2 

tensor([[3, 4, 5],
        [6, 7, 8]])

In [24]:
x-2

tensor([[-1,  0,  1],
        [ 2,  3,  4]])

In [25]:
x*2

tensor([[ 2,  4,  6],
        [ 8, 10, 12]])

In [26]:
x/2

tensor([[0.5000, 1.0000, 1.5000],
        [2.0000, 2.5000, 3.0000]])

In [27]:
# floor
x= x*100
x//3

tensor([[ 33,  66, 100],
        [133, 166, 200]])

In [28]:
x

tensor([[100, 200, 300],
        [400, 500, 600]])

In [29]:
# power
x**2

tensor([[ 10000,  40000,  90000],
        [160000, 250000, 360000]])

In [30]:
# ভাগ শেষ
x%2

tensor([[0, 0, 0],
        [0, 0, 0]])

# Element wise operation

In [31]:
torch.manual_seed(100)
a=torch.rand(2,3)
b=torch.rand(2,3)
print(a)
print(b)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])
tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])


In [32]:
a+b

tensor([[0.3744, 0.8587, 0.4706],
        [0.6019, 0.7982, 1.4895]])

In [33]:
a-b

tensor([[-0.1510,  0.7730,  0.0545],
        [ 0.3658,  0.5548,  0.0183]])

In [34]:
a*b

tensor([[0.0293, 0.0350, 0.0546],
        [0.0571, 0.0823, 0.5546]])

In [35]:
a/b

tensor([[ 0.4251, 19.0441,  1.2621],
        [ 4.0994,  5.5590,  1.0249]])

In [36]:
a**b

tensor([[0.5622, 0.9913, 0.7572],
        [0.9179, 0.9536, 0.8124]])

In [37]:
a%b

tensor([[0.1117, 0.0019, 0.0545],
        [0.0117, 0.0680, 0.0183]])

In [38]:
c=torch.tensor([-1, -2, -3, -4])
c

tensor([-1, -2, -3, -4])

In [39]:
torch.abs(c)

tensor([1, 2, 3, 4])

In [40]:
torch.neg(a)

tensor([[-0.1117, -0.8158, -0.2626],
        [-0.4839, -0.6765, -0.7539]])

In [41]:
d=torch.tensor([-1.5, -2.6, -3.1, -4])
torch.round(d)

tensor([-2., -3., -3., -4.])

In [42]:
torch.ceil(d)

tensor([-1., -2., -3., -4.])

In [43]:
e=torch.tensor([6, 200, 140, 500, 7])  # সব value গুলাকে একটা নিদিষ্ট rang এ নিয়ে আসা
torch.clamp(e, min=1, max=10)

tensor([ 6, 10, 10, 10,  7])

# Math Reduction Operations

In [44]:
f= torch.randint(size=(2, 3), low=0, high=10, dtype=torch.float32)
f

tensor([[8., 8., 4.],
        [4., 1., 0.]])

In [45]:
torch.sum(f)

tensor(25.)

In [46]:
torch.sum(f, dim=0) # colum  wise sum

tensor([12.,  9.,  4.])

In [47]:
torch.sum(f, dim=1) # row  wise sum

tensor([20.,  5.])

In [48]:
torch.mean(f)

tensor(4.1667)

In [49]:
torch.mean(f, dim=0) # colum  wise mean

tensor([6.0000, 4.5000, 2.0000])

In [50]:
torch.mean(f, dim=1) # raw  wise mean

tensor([6.6667, 1.6667])

In [51]:
torch.median(f)

tensor(4.)

In [52]:
torch.max(f)

tensor(8.)

In [53]:
torch.min(f)

tensor(0.)

In [54]:
torch.prod(f) # dot product

tensor(0.)

In [55]:
torch.std(f)

tensor(3.3714)

In [56]:
torch.var(f)

tensor(11.3667)

In [57]:
torch.argmax(f) # সব থেকে বড় সংখ্যার position বলে দিবে

tensor(0)

In [58]:
torch.argmin(f)

tensor(5)

# Math matrix opertions

In [59]:
torch.manual_seed(100)
m1=torch.randint(size=(2, 3), low=1, high=10)
m2=torch.randint(size=(2, 3), low=1, high=10)
print(m1)
print(m2)

tensor([[8, 8, 9],
        [9, 2, 8]])
tensor([[7, 2, 7],
        [3, 8, 9]])


```
matrix mul এ m1 এর কলাম আর m2 এর row সমান হতে হয়। তাই transpose করে নিতে হয়। বা size(3, 2) করে নিতে হবে
```

In [60]:
m2= m2.T 
m2

tensor([[7, 3],
        [2, 8],
        [7, 9]])

In [61]:
torch.matmul(m1,m2)

tensor([[135, 169],
        [123, 115]])

In [62]:
# dot product
vector1= torch.tensor([1, 2])
vector2= torch.tensor([3, 4])

torch.dot(vector1, vector2)

tensor(11)

In [63]:
m1

tensor([[8, 8, 9],
        [9, 2, 8]])

In [64]:
torch.transpose(m1, 0, 1)

tensor([[8, 9],
        [8, 2],
        [9, 8]])

In [65]:
h= torch.randint(size=(3, 3), low=0, high=10, dtype=torch.float32) # এটা সব সময় squre/ বর্গ matrix এর উপরে কাজ করে

torch.det(h)

tensor(-160.)

In [66]:
torch.inverse(h)

tensor([[-0.0500,  0.3250,  0.0250],
        [ 0.2000, -0.3000, -0.1000],
        [-0.0500, -0.0500,  0.1500]])

#  Comparision Operations

In [67]:
i = torch.randint(size=( 2, 3), low=0, high=10)
j = torch.randint(size=( 2, 3), low=0, high=10)

In [68]:
i

tensor([[7, 4, 6],
        [0, 1, 9]])

In [69]:
j

tensor([[9, 8, 0],
        [7, 0, 0]])

In [70]:
# greater than
i>j

tensor([[False, False,  True],
        [False,  True,  True]])

In [71]:
# less than
i<j

tensor([[ True,  True, False],
        [ True, False, False]])

In [72]:
# equal to
i==j

tensor([[False, False, False],
        [False, False, False]])

In [73]:
# not equal
i!=j

tensor([[True, True, True],
        [True, True, True]])

# Special Functions

In [74]:
k= torch.tensor([10, 20, 30])
k

tensor([10, 20, 30])

In [75]:
torch.log(k)

tensor([2.3026, 2.9957, 3.4012])

In [76]:
# exponential -> e এর power হিসবে আসবে [10, 20, 30]
torch.exp(k)

tensor([2.2026e+04, 4.8517e+08, 1.0686e+13])

In [77]:
torch.sqrt(k)

tensor([3.1623, 4.4721, 5.4772])

In [78]:
# sigmoid
torch.sigmoid(k)

tensor([1.0000, 1.0000, 1.0000])

In [79]:
# softmax
torch.softmax(k.float(), dim=0)

tensor([2.0611e-09, 4.5398e-05, 9.9995e-01])

In [80]:
torch.relu(k)

tensor([10, 20, 30])

# Inplace operations
```
 অন্য variable এর মধ্যে রাখলে জায়গার নষ্ট হবে, যখন বড় architer নিয়ে কাজ করব তখন full code crash করবে। তাই  জায়গা বাচানোর জন্য ওটার মধ্যে update করে রেখে দিব, এটাই inplace o perations
```

In [81]:
a= torch.tensor([1, 2, 3])
a

tensor([1, 2, 3])

In [83]:
b= a+ 5
b

tensor([6, 7, 8])

In [84]:
m= torch.rand(2, 3)
n= torch.rand(2, 3)

In [85]:
m

tensor([[0.4235, 0.0169, 0.2209],
        [0.9535, 0.7064, 0.1629]])

In [86]:
n

tensor([[0.8902, 0.5163, 0.0359],
        [0.6476, 0.3430, 0.3182]])

In [88]:
# in place operation

m.add_(n) # m টা এখানে update হয়ে গেছে, আলাদা variable লাগবে না

tensor([[2.2039, 1.0494, 0.2927],
        [2.2488, 1.3925, 0.7994]])

In [90]:
torch.relu_(m) # সব কিছুই inplace version আছে, নিচে underscore মানেই inplace

tensor([[2.2039, 1.0494, 0.2927],
        [2.2488, 1.3925, 0.7994]])

In [93]:
n.relu_() # এভাবেও করা যায়

tensor([[0.8902, 0.5163, 0.0359],
        [0.6476, 0.3430, 0.3182]])

# Copying a tensor

In [94]:
a= [1, 2, 3, 4, 5]
a

[1, 2, 3, 4, 5]

In [95]:
b=a

In [96]:
b[2]= 30
b

[1, 2, 30, 4, 5]

In [99]:
a #এখানে আমি a কে change করি নাই, তাও a চেঞ্জ হয়ে গেছে এই problem কে বলে python deep copy and shallow copy problem
# এখানে সমস্যা টা হল a আর b , same address এ assign হয়েছে

[1, 2, 30, 4, 5]

## solve with clone()

In [100]:
a= torch.tensor([1, 2, 3, 4, 5])
a

tensor([1, 2, 3, 4, 5])

In [101]:
b=a.clone()

In [102]:
b

tensor([1, 2, 3, 4, 5])

In [104]:
b[2]=30
b

tensor([ 1,  2, 30,  4,  5])

In [105]:
a

tensor([1, 2, 3, 4, 5])