In [ ]:
import torch as 
print(torch.__version__)

2.11.0+cu130


In [5]:
if torch.cuda.is_available():
    print('GPU is avilable')
    print(f'Device name {torch.cuda.get_device_name(0)}')
else:
    print('GPU is not avilable')

GPU is avilable
Device name NVIDIA GeForce RTX 3050 Ti Laptop GPU


In [8]:
a= torch.empty(2, 3)
a

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
type(a)

torch.Tensor

In [10]:
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [11]:
torch.ones(3, 4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [12]:
torch.rand(2, 3)

tensor([[0.7206, 0.8236, 0.6947],
        [0.5140, 0.1482, 0.7393]])

In [ ]:
torch.manual_seed(100) # এটা দিলে যত বারই run করি same value দিবে
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
torch.tensor([[1, 2, 3], [4, 5, 6]]) # নিজের বানানো array

tensor([[1, 2, 3],
        [4, 5, 6]])

In [15]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [18]:
print(torch.arange(0, 10, 2)) # 0 to 10 value দিবে ২ করে step
print(torch.arange(0, 10, 1)) # 0 to 10 value দিবে 1 করে step

tensor([0, 2, 4, 6, 8])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [21]:
torch.linspace(1, 10, 10)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

# Tensors Shape

In [22]:
x= torch.tensor([[1,2,3], [4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [23]:
x.shape

torch.Size([2, 3])

In [27]:
torch.empty_like(x) # x এর shape এর মত, empty tensor বানবে

tensor([[0, 0, 0],
        [0, 0, 0]])

In [28]:
torch.ones_like(x) # x এর shape এর মত, one নিয়ে tensor বানবে

tensor([[1, 1, 1],
        [1, 1, 1]])

In [29]:
torch.rand_like(x, dtype=torch.float32) # x এর shape এর মত, random (float বলে দিছি, অন্য কিছুও বলা যাইত) নিয়ে tensor বানবে

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

# Data types

In [30]:
x.dtype

torch.int64

In [32]:
torch.tensor([1.0, 2.3, 3.0, 4.5], dtype=torch.int32) # data টা float কিন্তু আমরা চাচ্ছি int এ

tensor([1, 2, 3, 4], dtype=torch.int32)

In [34]:
torch.tensor([1, 2, 4, 5], dtype=torch.float32) # data টা int কিন্তু আমরা চাচ্ছি float এ

tensor([1., 2., 4., 5.])

In [38]:
print('প্রথমে এটা int ছিল: ',x.dtype)
x=x.to(torch.float32)
print(x)
print('convert করে এখন এটাকে flot করা হল: ',x.dtype)

প্রথমে এটা int ছিল:  torch.float32
tensor([[1., 2., 3.],
        [4., 5., 6.]])
convert করে এখন এটাকে flot করা হল:  torch.float32


# Mathematical operations

In [39]:
x= torch.tensor([[1,2,3], [4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

```সব গুলা value এর সাথে +, -, *, / হয়ে যাবে```

In [ ]:
x+2 

tensor([[3, 4, 5],
        [6, 7, 8]])

In [41]:
x-2

tensor([[-1,  0,  1],
        [ 2,  3,  4]])

In [42]:
x*2

tensor([[ 2,  4,  6],
        [ 8, 10, 12]])

In [43]:
x/2

tensor([[0.5000, 1.0000, 1.5000],
        [2.0000, 2.5000, 3.0000]])

In [44]:
# floor
x= x*100
x//3

tensor([[ 33,  66, 100],
        [133, 166, 200]])

In [46]:
x

tensor([[100, 200, 300],
        [400, 500, 600]])

In [45]:
# power
x**2

tensor([[ 10000,  40000,  90000],
        [160000, 250000, 360000]])

In [47]:
# ভাগ শেষ
x%2

tensor([[0, 0, 0],
        [0, 0, 0]])

# Element wise operation