In [114]:
! pip install nltk

In [115]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
from collections import Counter
from torch.utils.data import Dataset, DataLoader
from nltk.tokenize import word_tokenize
import nltk

In [116]:
document = """The Last Train Journey

On a cold winter evening, Daniel arrived at the old railway station carrying a small leather bag.
The station was nearly empty except for a few passengers waiting quietly on wooden benches.
A loud whistle echoed through the air as the final train of the night slowly entered the platform.

Daniel checked the ticket in his pocket and walked toward the train.
The metal doors opened with a creaking sound and warm air rushed outside.
Inside the train, yellow lights flickered softly above rows of empty seats.

He chose a seat beside the window and placed his bag carefully near his feet.
As the train began to move, the city lights slowly disappeared behind thick clouds of fog.
Snow started falling gently outside while distant mountains appeared under the moonlight.

Across the aisle sat an elderly woman reading an old book with a blue cover.
Every few minutes she looked outside the window as if searching for something familiar.
Daniel noticed a silver necklace around her neck shaped like a small compass.

After several hours, the train stopped at a remote station surrounded by tall pine trees.
Very few people entered or left the train at that place.
A strange silence covered the station as the doors closed once again.

Curious about the woman, Daniel finally started a conversation.
The woman introduced herself as Eleanor and explained that she was returning to her hometown after many years.
She said the town was hidden deep within the northern mountains and was known for its beautiful frozen lake.

As the journey continued, Eleanor shared stories from her childhood.
She described colorful festivals, music performances, and lanterns floating across the lake during winter nights.
Daniel listened carefully while the train moved through snowy valleys and dark forests.

Near midnight, the train suddenly slowed down because heavy snow had covered the tracks ahead.
Passengers became nervous and began discussing possible delays.
Conductors moved through the cabins trying to calm everyone.

Daniel looked outside and saw workers removing snow under bright floodlights.
The freezing wind shook the train slightly while snow continued falling from the dark sky.
Despite the delay, Eleanor remained calm and continued telling her stories.

Several hours later, the tracks were finally cleared and the train resumed its journey.
The passengers sighed with relief as warm coffee was served throughout the cabins.
Daniel and Eleanor continued talking about travel, history, and forgotten places around the world.

Just before sunrise, the train reached the mountain town.
The station was small but beautifully decorated with glowing lamps and snow-covered rooftops.
People wearing thick winter coats walked slowly across the icy streets.

Before leaving, Eleanor handed Daniel a folded piece of paper.
Inside it was a drawing of the frozen lake along with a short message thanking him for the conversation.
Daniel smiled and carefully placed the paper inside his notebook.

As the train departed once again, Daniel stood on the platform watching the sunrise over the mountains.
The cold air, quiet streets, and distant church bells created a peaceful atmosphere he would never forget.
Years later, Daniel would still remember that mysterious winter journey and the stories shared by Eleanor on the last train of the night.
"""

In [117]:
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\skmah\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\skmah\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

# Tokenize

In [118]:
tokens= word_tokenize(document.lower())
tokens

['the',
 'last',
 'train',
 'journey',
 'on',
 'a',
 'cold',
 'winter',
 'evening',
 ',',
 'daniel',
 'arrived',
 'at',
 'the',
 'old',
 'railway',
 'station',
 'carrying',
 'a',
 'small',
 'leather',
 'bag',
 '.',
 'the',
 'station',
 'was',
 'nearly',
 'empty',
 'except',
 'for',
 'a',
 'few',
 'passengers',
 'waiting',
 'quietly',
 'on',
 'wooden',
 'benches',
 '.',
 'a',
 'loud',
 'whistle',
 'echoed',
 'through',
 'the',
 'air',
 'as',
 'the',
 'final',
 'train',
 'of',
 'the',
 'night',
 'slowly',
 'entered',
 'the',
 'platform',
 '.',
 'daniel',
 'checked',
 'the',
 'ticket',
 'in',
 'his',
 'pocket',
 'and',
 'walked',
 'toward',
 'the',
 'train',
 '.',
 'the',
 'metal',
 'doors',
 'opened',
 'with',
 'a',
 'creaking',
 'sound',
 'and',
 'warm',
 'air',
 'rushed',
 'outside',
 '.',
 'inside',
 'the',
 'train',
 ',',
 'yellow',
 'lights',
 'flickered',
 'softly',
 'above',
 'rows',
 'of',
 'empty',
 'seats',
 '.',
 'he',
 'chose',
 'a',
 'seat',
 'beside',
 'the',
 'window',
 'a

# Build vocabs

In [119]:
vocab= {'<unk>': 0}

In [120]:
for token in Counter(tokens).keys():
    if token not in vocab:
        vocab[token]= len(vocab)
        

#print
vocab

{'<unk>': 0,
 'the': 1,
 'last': 2,
 'train': 3,
 'journey': 4,
 'on': 5,
 'a': 6,
 'cold': 7,
 'winter': 8,
 'evening': 9,
 ',': 10,
 'daniel': 11,
 'arrived': 12,
 'at': 13,
 'old': 14,
 'railway': 15,
 'station': 16,
 'carrying': 17,
 'small': 18,
 'leather': 19,
 'bag': 20,
 '.': 21,
 'was': 22,
 'nearly': 23,
 'empty': 24,
 'except': 25,
 'for': 26,
 'few': 27,
 'passengers': 28,
 'waiting': 29,
 'quietly': 30,
 'wooden': 31,
 'benches': 32,
 'loud': 33,
 'whistle': 34,
 'echoed': 35,
 'through': 36,
 'air': 37,
 'as': 38,
 'final': 39,
 'of': 40,
 'night': 41,
 'slowly': 42,
 'entered': 43,
 'platform': 44,
 'checked': 45,
 'ticket': 46,
 'in': 47,
 'his': 48,
 'pocket': 49,
 'and': 50,
 'walked': 51,
 'toward': 52,
 'metal': 53,
 'doors': 54,
 'opened': 55,
 'with': 56,
 'creaking': 57,
 'sound': 58,
 'warm': 59,
 'rushed': 60,
 'outside': 61,
 'inside': 62,
 'yellow': 63,
 'lights': 64,
 'flickered': 65,
 'softly': 66,
 'above': 67,
 'rows': 68,
 'seats': 69,
 'he': 70,
 'chose

In [121]:
len(vocab)

284

# Extract sentence from data

In [122]:
input_sentences= document.split('\n')

In [123]:
input_sentences[0]

'The Last Train Journey'

In [124]:
def text_to_indices(sentence, vocab):
    numerical_sentence= []
    for token in sentence:
        if token in vocab:
            numerical_sentence.append(vocab[token])
        else:
            numerical_sentence.append(vocab['<unk>'])
            
    return numerical_sentence

In [125]:
input_numerical_sentence= []
for sentence in input_sentences:
    input_numerical_sentence.append(text_to_indices(word_tokenize(sentence.lower()), vocab))

In [126]:
input_numerical_sentence

[[1, 2, 3, 4],
 [],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14, 15, 16, 17, 6, 18, 19, 20, 21],
 [1, 16, 22, 23, 24, 25, 26, 6, 27, 28, 29, 30, 5, 31, 32, 21],
 [6, 33, 34, 35, 36, 1, 37, 38, 1, 39, 3, 40, 1, 41, 42, 43, 1, 44, 21],
 [],
 [11, 45, 1, 46, 47, 48, 49, 50, 51, 52, 1, 3, 21],
 [1, 53, 54, 55, 56, 6, 57, 58, 50, 59, 37, 60, 61, 21],
 [62, 1, 3, 10, 63, 64, 65, 66, 67, 68, 40, 24, 69, 21],
 [],
 [70, 71, 6, 72, 73, 1, 74, 50, 75, 48, 20, 76, 77, 48, 78, 21],
 [38, 1, 3, 79, 80, 81, 10, 1, 82, 64, 42, 83, 84, 85, 86, 40, 87, 21],
 [88, 89, 90, 91, 61, 92, 93, 94, 95, 96, 1, 97, 21],
 [],
 [98, 1, 99, 100, 101, 102, 103, 104, 101, 14, 105, 56, 6, 106, 107, 21],
 [108, 27, 109, 110, 111, 61, 1, 74, 38, 112, 113, 26, 114, 115, 21],
 [11, 116, 6, 117, 118, 119, 120, 121, 122, 123, 6, 18, 124, 21],
 [],
 [125, 126, 127, 10, 1, 3, 128, 13, 6, 129, 16, 130, 131, 132, 133, 134, 21],
 [135, 27, 136, 43, 137, 138, 1, 3, 13, 139, 140, 21],
 [6, 141, 142, 143, 1, 16, 38, 1, 54, 144, 145, 146

# training sequence form

In [127]:
traning_sequence= []
for sentence in input_numerical_sentence:
    for i in range(1, len(sentence)):
        traning_sequence.append(sentence[:i+1])

In [128]:
traning_sequence

[[1, 2],
 [1, 2, 3],
 [1, 2, 3, 4],
 [5, 6],
 [5, 6, 7],
 [5, 6, 7, 8],
 [5, 6, 7, 8, 9],
 [5, 6, 7, 8, 9, 10],
 [5, 6, 7, 8, 9, 10, 11],
 [5, 6, 7, 8, 9, 10, 11, 12],
 [5, 6, 7, 8, 9, 10, 11, 12, 13],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14, 15],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14, 15, 16],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14, 15, 16, 17],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14, 15, 16, 17, 6],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14, 15, 16, 17, 6, 18],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14, 15, 16, 17, 6, 18, 19],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14, 15, 16, 17, 6, 18, 19, 20],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14, 15, 16, 17, 6, 18, 19, 20, 21],
 [1, 16],
 [1, 16, 22],
 [1, 16, 22, 23],
 [1, 16, 22, 23, 24],
 [1, 16, 22, 23, 24, 25],
 [1, 16, 22, 23, 24, 25, 26],
 [1, 16, 22, 23, 24, 25, 26, 6],
 [1, 16, 22, 23, 24, 25, 26, 6, 27],
 [1, 16, 22, 23, 24, 25, 26, 6, 27, 28],
 [1, 16, 22, 23, 24, 2

In [129]:
len(traning_sequence)

555

In [130]:
traning_sequence[:5]

[[1, 2], [1, 2, 3], [1, 2, 3, 4], [5, 6], [5, 6, 7]]

In [131]:
len_list = []
for sequence in traning_sequence:
  len_list.append(len(sequence))

In [132]:
max(len_list)

25

In [133]:
# logic
[0]* (max(len_list)-len(sequence)) 
# এখানে আমার max len যদি 5 হয় ,
# তাহলে আমার [1, 2] value কে [0 0 0 1 2] করে দিবে। মানে সব গুলা সমান করে দিবে

[]

In [134]:
traning_sequence[0]

[1, 2]

In [135]:
padded_trainig_sequence= []
for sequence in traning_sequence:
    padded_trainig_sequence.append([0]* (max(len_list)-len(sequence)) + sequence)

In [136]:
len(padded_trainig_sequence[0])

25

In [137]:
padded_trainig_sequence[0]

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2]

# Tensor convert

In [138]:
padded_trainig_sequence= torch.tensor(padded_trainig_sequence, dtype=torch.long)

In [139]:
padded_trainig_sequence

tensor([[  0,   0,   0,  ...,   0,   1,   2],
        [  0,   0,   0,  ...,   1,   2,   3],
        [  0,   0,   0,  ...,   2,   3,   4],
        ...,
        [  0,   0, 158,  ...,   3,  40,   1],
        [  0, 158, 223,  ...,  40,   1,  41],
        [158, 223,  10,  ...,   1,  41,  21]])

In [140]:
X= padded_trainig_sequence[:, :-1]

In [141]:
X

tensor([[  0,   0,   0,  ...,   0,   0,   1],
        [  0,   0,   0,  ...,   0,   1,   2],
        [  0,   0,   0,  ...,   1,   2,   3],
        ...,
        [  0,   0, 158,  ...,   2,   3,  40],
        [  0, 158, 223,  ...,   3,  40,   1],
        [158, 223,  10,  ...,  40,   1,  41]])

In [142]:
y= padded_trainig_sequence[:, -1]

In [143]:
y

tensor([  2,   3,   4,   6,   7,   8,   9,  10,  11,  12,  13,   1,  14,  15,
         16,  17,   6,  18,  19,  20,  21,  16,  22,  23,  24,  25,  26,   6,
         27,  28,  29,  30,   5,  31,  32,  21,  33,  34,  35,  36,   1,  37,
         38,   1,  39,   3,  40,   1,  41,  42,  43,   1,  44,  21,  45,   1,
         46,  47,  48,  49,  50,  51,  52,   1,   3,  21,  53,  54,  55,  56,
          6,  57,  58,  50,  59,  37,  60,  61,  21,   1,   3,  10,  63,  64,
         65,  66,  67,  68,  40,  24,  69,  21,  71,   6,  72,  73,   1,  74,
         50,  75,  48,  20,  76,  77,  48,  78,  21,   1,   3,  79,  80,  81,
         10,   1,  82,  64,  42,  83,  84,  85,  86,  40,  87,  21,  89,  90,
         91,  61,  92,  93,  94,  95,  96,   1,  97,  21,   1,  99, 100, 101,
        102, 103, 104, 101,  14, 105,  56,   6, 106, 107,  21,  27, 109, 110,
        111,  61,   1,  74,  38, 112, 113,  26, 114, 115,  21, 116,   6, 117,
        118, 119, 120, 121, 122, 123,   6,  18, 124,  21, 126, 1

In [144]:
len(y)

555

In [145]:
len(X)

555

# Custom Dataset and Dataloader

In [146]:
class CustomDataset(Dataset):
    def __init__(self, X, y):
        self.X= X
        self.y= y
        
    def __len__(self):
        return self.X.shape[0]
    
    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]
        

In [147]:
dataset= CustomDataset(X, y)

In [148]:
len(dataset)

555

In [149]:
dataloader= DataLoader(dataset, batch_size=32, shuffle=True)

In [150]:
for input, output in dataloader:
    print(input, output)

tensor([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 126, 127, 223,  10,
           1, 197, 224, 149, 225,  50,   1,   3, 226, 166],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,  11, 111,  61],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0, 108,  27, 109],
        [  0,   0,   0,   0,   0,   0,   0, 110, 175, 176, 177,  10, 178, 179,
          10,  50, 180, 181,  98,   1, 169, 182,   8, 183],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   6,  33,  34,  35,  36,
           1,  37,  38,   1,  39,   3,  40,   1,  41,  42],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 110,
         175, 176, 177,  10, 178, 179,  10,  50, 180, 181],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,  38,   1,   4, 170,  10, 153, 171, 172, 173],
        [  0,   0,   0,   0

In [151]:
X.shape

torch.Size([555, 24])

In [152]:
y.shape

torch.Size([555])

In [153]:
X[0]

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1])

In [154]:
y[0]

tensor(2)

In [155]:
len(dataset)

555

In [156]:
len(vocab)

284

# LSTM Cell

In [157]:
class LSTMModel(nn.Module):
    def __init__(self, vocab_size):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size, 100)
        self.lstm = nn.LSTM(100, 150, batch_first=True) # batch_first=true করে দিলে batch_size, sequence_len, input_size হয়ে যায়। যার ফলে shape miss mass এর problem টা solve হয়ে যায়
        self.fc = nn.Linear(150, vocab_size
                            )
    def forward(self, x):
        embedded = self.embedding(x)
        intermediate_hidden_states, (final_hidden_state, final_cell_state) = self.lstm(embedded)
        output = self.fc(final_hidden_state.squeeze(0))
        return output

In [158]:
model = LSTMModel(len(vocab))

In [159]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [160]:
model.to(device)

LSTMModel(
  (embedding): Embedding(284, 100)
  (lstm): LSTM(100, 150, batch_first=True)
  (fc): Linear(in_features=150, out_features=284, bias=True)
)

# Training Loop

In [161]:
epochs = 50
learning_rate = 0.001
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

for epoch in range(epochs):
    total_loss = 0
    
    for batch_x, batch_y in dataloader:
        batch_x, batch_y = batch_x.to(device), batch_y.to(device)
        optimizer.zero_grad()
        output = model(batch_x)
        loss = criterion(output, batch_y)
        loss.backward()
        optimizer.step()
        total_loss = total_loss + loss.item()
        
    print(f'Epoch: {epoch + 1}, Loss: {total_loss: .4f}')

Epoch: 1, Loss:  101.2610
Epoch: 2, Loss:  95.4300
Epoch: 3, Loss:  87.6959
Epoch: 4, Loss:  81.7624
Epoch: 5, Loss:  76.1775
Epoch: 6, Loss:  71.0317
Epoch: 7, Loss:  65.4063
Epoch: 8, Loss:  60.8096
Epoch: 9, Loss:  55.2949
Epoch: 10, Loss:  49.4257
Epoch: 11, Loss:  45.1556
Epoch: 12, Loss:  40.3715
Epoch: 13, Loss:  35.6138
Epoch: 14, Loss:  31.7019
Epoch: 15, Loss:  27.7452
Epoch: 16, Loss:  24.9948
Epoch: 17, Loss:  21.8271
Epoch: 18, Loss:  19.4359
Epoch: 19, Loss:  17.2055
Epoch: 20, Loss:  15.2250
Epoch: 21, Loss:  13.6770
Epoch: 22, Loss:  12.2445
Epoch: 23, Loss:  10.9390
Epoch: 24, Loss:  9.9618
Epoch: 25, Loss:  9.0959
Epoch: 26, Loss:  8.1392
Epoch: 27, Loss:  7.3967
Epoch: 28, Loss:  6.8936
Epoch: 29, Loss:  6.3197
Epoch: 30, Loss:  5.8250
Epoch: 31, Loss:  5.5685
Epoch: 32, Loss:  5.1406
Epoch: 33, Loss:  4.9048
Epoch: 34, Loss:  4.5365
Epoch: 35, Loss:  4.2727
Epoch: 36, Loss:  4.1855
Epoch: 37, Loss:  3.8848
Epoch: 38, Loss:  3.7091
Epoch: 39, Loss:  3.7345
Epoch: 40,

# Prediction

In [164]:
def prediction(model, vocab, text):
    # tokenize
    tokenized_text = word_tokenize(text.lower())
    
    # numerical indices
    numerical_text = text_to_indices(tokenized_text,vocab)
    
    # padding
    padded_text = torch.tensor([0]* (25-len(numerical_text)) + numerical_text , dtype=torch.long).unsqueeze(0)
    
    # টেনসরটিকে মডেলে পাঠানোর আগে device-এ (GPU) ট্রান্সফার করুন
    padded_text = padded_text.to(device)
    
    # send to model
    output = model(padded_text)
    
    # predicted index
    value, index = torch.max(output,dim=1)
    
    # merge with text (GPU tensor থেকে পাইথন ইন্টিজারে নিতে .item() ব্যবহার করা হয়েছে)
    return text + " " + list(vocab.keys())[index.item()]

In [168]:
prediction(model,vocab,"On a cold winter")

'On a cold winter evening'

# Generate Automatically

In [169]:
import time
num_tokens = 20
input_text = 'Daniel checked the ticket'

for i in range(num_tokens):
    output_text = prediction(model, vocab, input_text)
    print(output_text)
    input_text = output_text
    time.sleep(0.5)

Daniel checked the ticket in
Daniel checked the ticket in his
Daniel checked the ticket in his pocket
Daniel checked the ticket in his pocket and
Daniel checked the ticket in his pocket and walked
Daniel checked the ticket in his pocket and walked toward
Daniel checked the ticket in his pocket and walked toward the
Daniel checked the ticket in his pocket and walked toward the train
Daniel checked the ticket in his pocket and walked toward the train .
Daniel checked the ticket in his pocket and walked toward the train . .
Daniel checked the ticket in his pocket and walked toward the train . . .
Daniel checked the ticket in his pocket and walked toward the train . . . .
Daniel checked the ticket in his pocket and walked toward the train . . . . .
Daniel checked the ticket in his pocket and walked toward the train . . . . . .
Daniel checked the ticket in his pocket and walked toward the train . . . . . . .
Daniel checked the ticket in his pocket and walked toward the train . . . . . . . .

# Accuracy Calculation

In [170]:
def calculate_accuracy(model, dataloader, device):
    model.eval()
    correct = 0
    total = 0
    
    with torch.no_grad():
        for batch_x, batch_y in dataloader:
            batch_x, batch_y = batch_x.to(device), batch_y.to(device)
            
            # get moel prediction
            output = model(batch_x)
            
            # et the predictec word indices
            _, predicted = torch.max(output, dim=1)
            
            # compare with actual label
            correct += (predicted == batch_y).sum().item()
            total += batch_y.size(0)
            
        accuracy = correct / total * 100
        return accuracy

In [171]:
accuracy = calculate_accuracy(model, dataloader, device)
print(f'Model accuracy {accuracy: .4f}%')

Model accuracy  96.9369%
